### ISSUE TITLE
Link down for improved version

### ISSUE THREAD

**Issue by KoolenDasheppi** [EthanSK/Youtuber-Speech-Word-Detection-Bot#1]
Is there a mirror somewhere? Would like to try out the new version of this. XP

**Comment by MalachiMassey** [comment]
I clicked the link and it took me to a page asking for a password. I saw no place to create an account or any clue what the password was. I'd love to try this for myself too. Is there any chance we could ever see a python version of this? That would go over big.

**Comment by KoolenDasheppi** [comment]
Forgot about this to be honest, but now I'm re-interested. It seems he's trying to put a new link, but as of writing this it goes to a blank Wix page. Also he had a GitHub repo linked but now it's 404'ing. Guess we have to wait a bit for him to fix the website.

**Comment by EthanSK** [comment]
Good things are coming soon. very soon.

**Comment by EthanSK** [comment]
Ladies and gentlemen: The future.

https://www.youtubewordfinder.com/

**Comment by MalachiMassey** [comment]
Is there also an updated method of using the auto-tune feature?
